@"
FROM ruby:3.4.2-alpine

RUN apk add --no-cache build-base postgresql-dev tzdata nodejs bash

WORKDIR /app

COPY Gemfile ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
"@
