@"
source "https://rubygems.org"
ruby "3.4.2"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.8"
gem "faraday", "~> 2.9"

group :development, :test do
  gem "debug", platforms: [:mri, :mingw, :x64_mingw]
  gem "dotenv-rails"
end
"@
